import base64
import httpx
from fastapi import HTTPException

from ..models.pipeline import GithubPushRequest
from .generator import get_generated_files


async def push_to_github(request: GithubPushRequest) -> str:
    """Push generated infrastructure files to a GitHub repository."""
    files = get_generated_files(request.config)
    token = request.token
    repo_name = request.repo_name
    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }

    async with httpx.AsyncClient() as client:
        # Get authenticated user
        user_resp = await client.get("https://api.github.com/user", headers=headers)
        if user_resp.status_code != 200:
            raise HTTPException(status_code=401, detail="Invalid GitHub token")
        username = user_resp.json()["login"]

        # Create repository
        create_resp = await client.post(
            "https://api.github.com/user/repos",
            headers=headers,
            json={"name": repo_name, "private": request.private, "auto_init": False},
        )
        if create_resp.status_code not in (200, 201):
            raise HTTPException(
                status_code=400,
                detail=create_resp.json().get("message", "Failed to create repo"),
            )

        # Push all files
        files_to_push = {
            "Dockerfile": files["dockerfile"],
            "compose.yaml": files["compose"],
            "k8s/deployment.yaml": files["k8s_deployment"],
            "k8s/service.yaml": files["k8s_service"],
            "helm/Chart.yaml": files["helm_chart"],
            "helm/values.yaml": files["helm_values"],
            "helm/templates/deployment.yaml": files["helm_deployment"],
            "README.md": f"# {repo_name}\n\nGenerated by DevFlow Studio for {request.config.framework}.",
        }
        for path, content in files_to_push.items():
            encoded = base64.b64encode(content.encode()).decode()
            await client.put(
                f"https://api.github.com/repos/{username}/{repo_name}/contents/{path}",
                headers=headers,
                json={"message": f"feat: add {path}", "content": encoded},
            )

    return f"https://github.com/{username}/{repo_name}"

