import io
import zipfile

from fastapi import APIRouter
from fastapi.responses import StreamingResponse

from ..models.pipeline import PipelineConfig
from ..services.pipeline import generate_pipeline_content

router = APIRouter()


@router.post("/generate/pipeline")
def generate_pipeline(config: PipelineConfig):
    return {"pipeline": generate_pipeline_content(config)}


@router.post("/export/pipeline")
def export_pipeline_zip(config: PipelineConfig):
    content = generate_pipeline_content(config)

    # Determine file name based on target
    file_names = {
        "github-actions": ".github/workflows/ci.yml",
        "gitlab-ci": ".gitlab-ci.yml",
        "azure-devops": "azure-pipelines.yml",
    }
    file_name = file_names.get(config.target, "pipeline.yml")
    readme_content = (
        f"# {config.app_name} - CI/CD Pipeline\n\n"
        f"Generated by DevFlow Studio.\n\n"
        f"Target: {config.target}\n"
        f"Stages: {', '.join(config.stages)}"
    )

    zip_buffer = io.BytesIO()
    with zipfile.ZipFile(zip_buffer, "a", zipfile.ZIP_DEFLATED, False) as zip_file:
        zip_file.writestr(file_name, content)
        zip_file.writestr("README.md", readme_content)

    zip_buffer.seek(0)
    return StreamingResponse(
        zip_buffer,
        media_type="application/zip",
        headers={"Content-Disposition": f"attachment; filename={config.app_name}-pipeline.zip"},
    )

